### ISSUE TITLE
Automatic aligner failed in spanish

### ISSUE THREAD

**Issue by JudicaelCandyVoice** [brigittebigi/sppas#12]
Hello.

First of all, thanks a lot for your software!

I have this error message when I try to align sentences in spanish. 

[  ERROR  ] The automatic aligner 'julius' failed to perform segmentation.
 ...  ...  ...  ... [   INFO   ] Error: rdhmmdef_data: HMM "dx" is defined more than twice

I have this problem only in spanish. Julius is, of course, installed, the quality of audio is pretty good and the transcription matches perfectly the audio... 

Is there something I'm missing?

Tanks for your help

**Comment by brigittebigi** [comment]
Many thanks for reporting this bug.
This is solved in version 1.9.4.
--Brigitte
