### ISSUE TITLE
Segment Cantonese with text format data

### ISSUE THREAD

**Issue by secsilm** [brigittebigi/sppas#14]
Hi, can this lib segment text Cantonese, not audio format?

**Comment by brigittebigi** [comment]
yes.

The method is described here: 

> _Roxana Fung, Brigitte Bigi (2015).
> Automatic word segmentation for spoken Cantonese.
> In Oriental COCOSDA and Conference on Asian Spoken Language Research and Evaluation (O-COCOSDA/CASLRE), pp. 196-201._
> 

"Text Normalization" can segment texts of any format supported by SPPAS (xra, textgrid, eaf, trs, txt...). See the documentation, chapter 3.

--Brigittte

**Comment by secsilm** [comment]
Thanks for your reply. I read the paper and found that you've done a evaluation on the dataset contained written Chinese from Xinhuanews, Sinorama news magazine, and Hong Kong News.

But I can't find any relative code in the paper and [doc](http://www.sppas.org/index.html). Could you please give me a example code or tell me where I can find the code?

Thanks.

**Comment by brigittebigi** [comment]
The source code of the "Text Normalization" is in the package "sppas/src/annotations/TextNorm".
The script "sppas/bin/normalize.py" allows to use it.
