### ISSUE TITLE
Alignment seems to fail if there are spaces in the file path

### ISSUE THREAD

**Issue by joshisanonymous** [brigittebigi/sppas#15]
I know there's a message that says that the xra token cannot contain whitespace, or something to that effect, but this doesn't make it super clear that neither the path nor the filename can contain spaces. Also, not that I know Python, but would it be possible to simply add some quotation marks somewhere so that paths/filenames with spaces will work, too?

**Comment by brigittebigi** [comment]
Hi,
you're right, quotation marks are required... and they are everywhere it's needed in SPPAS. But I still don't know why about 5% of the users have problems with spaces in file names (a filename and a path is the same thing). I've made a lot of tests on several computers + unittests, but never found why this problem "randomly" occurs.
