### ISSUE TITLE
Forced Alginment fail: *dfa.forward files for julius?

### ISSUE THREAD

**Issue by jl1101** [brigittebigi/sppas#23]
Hi,

Forced alignment using julius does not work for me in any language.  Based on the error log below and what I have found in the working directory, it seems that SPPAS does not generate some _*dfa.forward_ files while julius reads.

`Julius failed to align the transcription with the audio file.
Error: gzfile: unable to open /tmp/sppas_tmp_2020-06-08_7121_271045/track_000002.dfa.forward
Error: init_dfa: failed to open /tmp/sppas_tmp_2020-06-08_7121_271045/track_000002.dfa.forward`

My environment is Debian 10.  Both SPPAS and Julius are compiled from the respective latest releases.

Thanks!

Joe

**Comment by brigittebigi** [comment]
This error occurs for recent versions of Julius (4.5+), older versions are ok. This issue solved in SPPAS-3.3.
